version: "2"

checks:
  method-lines:
    config:
      threshold: 35

exclude_paths:
- "UI/"
- "server/docs"
- "server/tests"
- "client/tests"
- "client/e2e-tests"
- "client/src/**/*.spec.jsx"
- "client/src/**/*.test.js"
- ".nyc_output/"
- "node_modules/"
- "server/src/models"
- "server/src/seeders"
- "server/src/migrations"
- "server/src/validations"
